### ISSUE TITLE
Error Launching app

### ISSUE THREAD

**Issue by DELJN** [emodyz/launcher-ezgames.eu#22]
Hey there,
i get a probleme after the command "npm run dev". I dont know if i install all sucessfull. 
I have screenshots maybe they cold help.
Error: https://www2.pic-upload.de/img/34742132/error.jpg
Command1: https://www2.pic-upload.de/img/34742144/page1.jpg
Command2: https://www2.pic-upload.de/img/34742146/page2.jpg

Hope you can help me and sry for my bad englich im from germany ;D

**Comment by FlashModz** [comment]
Hello,

Config is missing in your app :)

**Comment by DELJN** [comment]
Ok ty found it and know it works. 👍

**Comment by FlashModz** [comment]
Now problems :)
Bye and Good play 👍
